"""Added name and email to User model

Revision ID: b0b0db31b581
Revises: 0b37574e86e8
Create Date: 2025-04-22 18:56:44.618317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b0db31b581'
down_revision = '0b37574e86e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('contact')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.VARCHAR(length=20), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
